name: MIV-CRAFT-FINAL
on:
  workflow_dispatch:

jobs:
  run-server:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Libraries
        run: |
          sudo apt update
          sudo apt install -y wget unzip libcurl4 libssl-dev grep

      - name: Download & Run
        run: |
          # هذه الحركة تجلب أحدث رابط تحميل تلقائياً من موقع ماينكرافت الرسمي
          LATEST_URL=$(curl -s https://www.minecraft.net/en-us/download/server/bedrock | grep -o 'https://minecraft.azureedge.net/bin-linux/[^"]*')
          echo "Downloading from: $LATEST_URL"
          wget $LATEST_URL -O server.zip
          
          unzip -o server.zip -d server
          cd server
          chmod +x bedrock_server
          
          # تشغيل السيرفر
          LD_LIBRARY_PATH=. ./bedrock_server
