name: MIV CRAFT 16GB RAM
on: workflow_dispatch

jobs:
  run-minecraft:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: System Info (To see your 16GB RAM)
        run: free -h

      - name: Install & Run Server
        run: |
          sudo apt update
          wget https://minecraft.azureedge.net/bin-linux/bedrock-server-1.20.73.01.zip
          unzip bedrock-server-*.zip -d server
          cd server
          chmod +x bedrock_server
          LD_LIBRARY_PATH=. ./bedrock_server
