name: MIV-CRAFT-1.21
on:
  workflow_dispatch:

jobs:
  run-server:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: System Setup
        run: |
          sudo apt update
          sudo apt install -y wget unzip libcurl4 libssl-dev
          rm -rf server server.zip

      - name: Download 1.21 and Start
        run: |
          # رابط إصدار 1.21.1.03 المستقر
          URL="https://minecraft.azureedge.net/bin-linux/bedrock-server-1.21.1.03.zip"
          
          wget --no-check-certificate $URL -O server.zip
          unzip -o server.zip -d server
          
          cd server
          chmod +x bedrock_server
          
          # تشغيل السيرفر مع ضبط المكتبات
          LD_LIBRARY_PATH=. ./bedrock_server
